export let modes = [
    { id: 1, name: "ALL ON" },
    { id: 2, name: "STRIP RAINBOW FADE" },
    { id: 3, name: "RAINBOW LOOP" },
    { id: 4, name: "RANDOM BURST" },
    { id: 5, name: "CYLON v1" },
    { id: 6, name: "CYLON v2" },
    { id: 7, name: "POLICE LIGHTS SINGLE" },
    { id: 8, name: "POLICE LIGHTS SOLID" },
    { id: 9, name: "STRIP FLICKER" },
    { id: 10, name: "PULSE COLOR BRIGHTNESS" },
    { id: 11, name: "PULSE COLOR SATURATION" },
    { id: 12, name: "VERTICAL SOMETHING" },
    { id: 13, name: "CELL AUTO - RULE 30 (RED)" },
    { id: 14, name: "MARCH RANDOM COLORS" },
    { id: 15, name: "MARCH RWB COLORS" },
    { id: 16, name: "RADIATION SYMBOL" },
    { id: 19, name: "SIN WAVE BRIGHTNESS" },
    { id: 20, name: "POP LEFT/RIGHT" },
    { id: 21, name: "QUADRATIC BRIGHTNESS CURVE" },
    { id: 23, name: "VERITCAL RAINBOW" },
    { id: 24, name: "PACMAN" },
    { id: 25, name: "RANDOM COLOR POP" },
    { id: 26, name: "EMERGECNY STROBE" },
    { id: 27, name: "RGB PROPELLER" },
    { id: 28, name: "KITT" },
    { id: 29, name: "MATRIX RAIN" },
    { id: 30, name: "colorWipe" },
    { id: 31, name: "CylonBounce" },
    { id: 32, name: "Fire" },
    { id: 33, name: "NewKITT" },
    { id: 34, name: "rainbowCycle" },
    { id: 35, name: "rainbowTwinkle" },
    { id: 36, name: "RunningLights" },
    { id: 37, name: "Sparkle" },
]