export let modes = [
    { id: 1, name: "ALL ON", color: "purple" , description: "Включает все светодиоды"},
    { id: 2, name: "SRF", color: "mint" },
    { id: 3, name: "RAINBOW LOOP", color: "yellowPink", description: "Радуга"},
    { id: 4, name: "RANDOM BURST", color: "sky" },
    { id: 5, name: "CYLON v1", color: "pinkBlue" },
    { id: 6, name: "CYLON v2", color: "yellow" },
    { id: 7, name: "POLICE LIGHTS SINGLE", color: "red" },
    { id: 8, name: "POLICE LIGHTS SOLID", color: "sea" },
    { id: 9, name: "STRIP FLICKER", color: "blueYellow" },
    { id: 10, name: "PULSE COLOR BRIGHTNESS", color: "blackSea" },
    { id: 11, name: "PULSE COLOR SATURATION" },
    { id: 12, name: "VERTICAL SOMETHING" },
    { id: 13, name: "CELL AUTO - RULE 30 (RED)" },
    { id: 14, name: "MARCH RANDOM COLORS" },
    { id: 15, name: "MARCH RWB COLORS" },
    { id: 16, name: "RADIATION SYMBOL" },
    { id: 19, name: "SIN WAVE BRIGHTNESS" },
    { id: 20, name: "POP LEFT/RIGHT" },
    { id: 21, name: "QUADRATIC BRIGHTNESS CURVE" },
    { id: 23, name: "VERITCAL RAINBOW" },
    { id: 24, name: "PACMAN" },
    { id: 25, name: "RANDOM COLOR POP" },
    { id: 45, name: "BouncingBalls" },
    { id: 35, name: "Fire" },
    { id: 43, name: "theater chase rainbow" }

]