export let modes = [
    { id: 0, name: "ALL OFF", description: "Выключает все светодиоды" },
    { id: 1, name: "ALL ON", description: "Включает все светодиоды" },
    { id: 2, name: "SRF", description: "Плавное переключение цветов" },
    { id: 3, name: "RAINBOW LOOP", description: "Радуга" },
    { id: 4, name: "RANDOM BURST", description: "Гирлянда" },
    { id: 5, name: "CYLON v1" },
    { id: 6, name: "CYLON v2" },
    { id: 7, name: "POLICE LIGHTS SINGLE", description: "Полицейские мигалки" },
    { id: 8, name: "POLICE LIGHTS SOLID", description: "Плавные полицейские мигалки" },
    { id: 9, name: "STRIP FLICKER" },
    { id: 10, name: "PULSE COLOR BRIGHTNESS" },
    { id: 11, name: "PULSE COLOR SATURATION" },
    { id: 12, name: "VERTICAL SOMETHING" },
    { id: 13, name: "CELL AUTO - RULE 30 (RED)" },
    { id: 14, name: "MARCH RANDOM COLORS" },
    { id: 15, name: "MARCH RWB COLORS" },
    { id: 16, name: "RADIATION SYMBOL" },
    { id: 19, name: "SIN WAVE BRIGHTNESS" },
    { id: 20, name: "POP LEFT/RIGHT" },
    { id: 21, name: "QUADRATIC BRIGHTNESS CURVE" },
    { id: 23, name: "VERITCAL RAINBOW", description: "Радуга с двух сторон" },
    { id: 24, name: "PACMAN", description: " Pacman :D" },
    { id: 25, name: "RANDOM COLOR POP" },
    { id: 45, name: "BouncingBalls" },
    { id: 35, name: "Fire" },
    { id: 43, name: "theater chase rainbow" }

]